/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppWorkersRouteImport } from './routes/app.workers'
import { Route as AppShiftsRouteImport } from './routes/app.shifts'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppServicesRouteImport } from './routes/app.services'
import { Route as AppReportsRouteImport } from './routes/app.reports'
import { Route as AppProductsRouteImport } from './routes/app.products'
import { Route as AppPosRouteImport } from './routes/app.pos'
import { Route as AppCashRouteImport } from './routes/app.cash'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkersRoute = AppWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AppRoute,
} as any)
const AppShiftsRoute = AppShiftsRouteImport.update({
  id: '/shifts',
  path: '/shifts',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServicesRoute = AppServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppCashRoute = AppCashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/cash': typeof AppCashRoute
  '/app/pos': typeof AppPosRoute
  '/app/products': typeof AppProductsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/workers': typeof AppWorkersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/cash': typeof AppCashRoute
  '/app/pos': typeof AppPosRoute
  '/app/products': typeof AppProductsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/workers': typeof AppWorkersRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/app/cash': typeof AppCashRoute
  '/app/pos': typeof AppPosRoute
  '/app/products': typeof AppProductsRoute
  '/app/reports': typeof AppReportsRoute
  '/app/services': typeof AppServicesRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/shifts': typeof AppShiftsRoute
  '/app/workers': typeof AppWorkersRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/cash'
    | '/app/pos'
    | '/app/products'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/shifts'
    | '/app/workers'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/app/cash'
    | '/app/pos'
    | '/app/products'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/shifts'
    | '/app/workers'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/app/cash'
    | '/app/pos'
    | '/app/products'
    | '/app/reports'
    | '/app/services'
    | '/app/settings'
    | '/app/shifts'
    | '/app/workers'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workers': {
      id: '/app/workers'
      path: '/workers'
      fullPath: '/app/workers'
      preLoaderRoute: typeof AppWorkersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/shifts': {
      id: '/app/shifts'
      path: '/shifts'
      fullPath: '/app/shifts'
      preLoaderRoute: typeof AppShiftsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/services': {
      id: '/app/services'
      path: '/services'
      fullPath: '/app/services'
      preLoaderRoute: typeof AppServicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/reports': {
      id: '/app/reports'
      path: '/reports'
      fullPath: '/app/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pos': {
      id: '/app/pos'
      path: '/pos'
      fullPath: '/app/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/cash': {
      id: '/app/cash'
      path: '/cash'
      fullPath: '/app/cash'
      preLoaderRoute: typeof AppCashRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCashRoute: typeof AppCashRoute
  AppPosRoute: typeof AppPosRoute
  AppProductsRoute: typeof AppProductsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppServicesRoute: typeof AppServicesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShiftsRoute: typeof AppShiftsRoute
  AppWorkersRoute: typeof AppWorkersRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCashRoute: AppCashRoute,
  AppPosRoute: AppPosRoute,
  AppProductsRoute: AppProductsRoute,
  AppReportsRoute: AppReportsRoute,
  AppServicesRoute: AppServicesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShiftsRoute: AppShiftsRoute,
  AppWorkersRoute: AppWorkersRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
